name: WILDERPRINT
favicon: null
layout_spectrum: 0.00542
typography_spectrum: 0.6145
title: Wilder Print - Offset and Direct Digital Printing in Orange County California
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181717'
    - '#dd2d6c'
    - '#02adc1'
    - '#797777'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
