name: WILDERPRINT
favicon: null
layout_spectrum: 0.14636870590038598
typography_spectrum: 0.6939707924611866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181717'
    - '#dd2d6c'
    - '#02adc1'
    - '#797777'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
